theme: jekyll-theme-cayman
title: Dulce M Mariscal Olivares 
description: PhD student at the University of Pittsburgh
social-network-links:
  email: "dum5@pitt.edu"
  twitter: DulceMMariscal
  linkedin: https://www.linkedin.com/in/dulcemariscal/
  rss: false
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
